[bumpver]
current_version = "2025.1001-dev"
version_pattern = "YYYY.BUILD[-TAG]"

[[file_patterns]]
file = "CHANGELOG.md"
search = '^## \[{version}\] - \d{4}-\d{2}-\d{2} <!-- {bumpver} -->'

[[file_patterns]]
file = "pyproject.toml"
search = 'current_version = "{current_version}"  # {{bumpver}}'
