[bumpver]
current_version = "2025.1001-alpha"
version_pattern = "YYYY.BUILD[-TAG]"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = false

[bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"'
]
"CHANGELOG.md" = [
    '## [{version}] - {timestamp} <!-- {bumpver} -->'
]