[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "astralengine"
version = "2025.1004-dev"
description = "Test"

[tool.black]
line-length = 100
