[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "astralengine"
version = "2025.1002-dev"
description = "Test"

[tool.black]
line-length = 100

[project.scripts]
astral = "astraltrail.launch_astral:main"