[bumpver]
current_version = "0.1.0"
version_pattern = "MAJOR.MINOR.PATCH"

# Files to update
files = [
    "pyproject.toml",
    "CHANGELOG.md"
]

# Optional: tag format for Git
tag_format = "v{version}"